### ISSUE TITLE
Masks to COCO format

### ISSUE THREAD

**Issue by sri9s** [IDEACVR/DINO#101]
How do I generate COCO format dataset from a dataset of instance masks?

**Comment by SuperHenry2333** [comment]
Say you have an instance mask represented as a polygon [(x_0, y_0), (x_1, y_1), ..., (x_N, y_N)]. You can have the upper left corner of the bbox as (min{x_i}, min{y_i}) and  the lower right corner of the bbox as (max{x_i}, max{y_i}).

**Comment by sri9s** [comment]
Thanks @SuperHenry2333 for the reply
