### ISSUE TITLE
ImageNet Pretrained Swin Weight

### ISSUE THREAD

**Issue by artest08** [IDEACVR/DINO#14]
Hello, thanks for the release of the code of this amazing study.

I want to ask that, is there a pre-trained imagenet backbone weights for the swin transformer in this repo? Maybe, it might be useful for replicating the swin transformer results of the paper.

Thank in advance

**Comment by SlongLiu** [comment]
Thanks for your suggestions. We will add Swin Transformer supports in the next update.

**Comment by JarintotionDin** [comment]
Thanks for the release.
How about providing the pre-trained model on object365, so we can reproduce the SOTA on CoCo.
