### ISSUE TITLE
about the improvements over the results in the paper

### ISSUE THREAD

**Issue by chensnathan** [IDEACVR/DINO#17]
Hi, thanks for releasing the code of the excellent work (DINO). 

It seems that the released code achieves better results than the ones in the DINO paper (49.0 mAP vs. 47.9 mAP for 12 epochs with DINO-4scale). Are there some further improvements provided in this repo?

It will be much appreciated if more details about the improvements are provided. Thanks in advance.

**Comment by chensnathan** [comment]
Thanks for your quick response. 
For the initialization of the parameters in deformable attention, do you mean [the code in L232-L234](https://github.com/IDEACVR/DINO/blob/main/models/dino/deformable_transformer.py#L234) are not included in the initial version?

**Comment by SuperHenry2333** [comment]
yes

**Comment by chensnathan** [comment]
Got it. Thanks a lot!
