### ISSUE TITLE
The decription of Deformable DETR is wrong

### ISSUE THREAD

**Issue by yuexi999** [IDEACVR/DINO#2]
![image](https://user-images.githubusercontent.com/101444292/158006075-510cd934-e57b-4054-b633-c0af2cffd6c4.png)

Deformable DETR doesn't formulate the queries as anchor points.

Actually, the query formulation of Deformable DETR is the same as the original DETR, i.e. a set of [learned embeddings](https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/models/deformable_detr.py#L58).

Instead, Deformable DETR predicts the reference points/anchor point by the queries.

**Comment by IDEACVR** [comment]
Thanks for pointing out the issue. We will fix it in the next version.
