### ISSUE TITLE
There is no optimizer.zero_grad() in training without amp.

### ISSUE THREAD

**Issue by Yamameeee** [IDEACVR/DINO#20]
Thank you for sharing your great work.

When trainning without amp, there is no optimizer.zero_grad(), is this intentional?
Did you forget to write it down?
If you use amp, are these taining results different?

[here](https://github.com/IDEACVR/DINO/blob/048823bbfe4e4a320a281525f8c1ecfae1d3582a/engine.py#L82)

**Comment by SuperHenry2333** [comment]
Thank you for your reminder. We have fixed the bug. The bug does not affect the result much because the grads after clip_grad_norm_() will be very small compared with the grads before clip_grad_norm_(). 
For your second question, using amp does not affect the result much.

**Comment by Yamameeee** [comment]
Thanks!

There was no optimizer.zero_grad() in DN and DAB as well.
