### ISSUE TITLE
obj365 checkpoint

### ISSUE THREAD

**Issue by gavin-usyd** [IDEACVR/DINO#21]
Dear authors,

Thanks for the excellent work.
May I ask, do you have the plan to release the obj365 pretraining checkpoints?

Thanks.

**Comment by FengLi-ust** [comment]
We have no plan to release this model for now, as the released models are strong enough. 
We will consider releasing this large model after this paper gets peer-reviewed. 
Stay tuned! Thank you for your understanding and patience.

**Comment by gavin-usyd** [comment]
Understand. Thanks for your prompt reply:)
