### ISSUE TITLE
training logs

### ISSUE THREAD

**Issue by jwyang** [IDEACVR/DINO#22]
Hi, thanks for the brilliant work! 

I am wondering whether you could provide the training logs for your released checkpoints so that we can track the training progress. thanks!

best,

**Comment by SuperHenry2333** [comment]
Thank you for your interest. We have just uploaded the training log https://drive.google.com/drive/folders/1LrH68UBI9taubHQzhDf3R8gjFP8IiqJO.

**Comment by jwyang** [comment]
Just saw the update, thanks a lot!
