### ISSUE TITLE
Fine tuning guide with custom dataset using pretrained coco model

### ISSUE THREAD

**Issue by yspaik** [IDEACVR/DINO#23]
I am trying to train a dino model and using the model, fine tune a dino model with my dataset.
I trained dino mode on the coco dataset at 12 epochs through the swin large 4 scale config
Then load the weights as a pretrained model to fine-tune it with my custom dataset.
 
Because the dataset I am trying to fine tune has different num_classes, so I will have to change the prediction layer num classes output and start fine tuning training.

How should I tweak the config for reuse? Or what part of the code should be modified? 
I'd like to get the guide.

Regards,
Keanu

**Comment by gd1925** [comment]
Hi!
The "dn_labebook_size" from the config file has to be changed to the number of classes in your custom dataset..

**Comment by SlongLiu** [comment]
When fine-tuning a COCO pre-trained model on your custom dataset, the main difference between two datasets is the number of classes. 

As said by @gd1925, the arg "dn_labebook_size" should be equal to or larger than the number of classes.

When loading pre-trained models, we suggest using "--pretrain_model_path" to specify a pre-trained model, and using "--finetune_ignore label_enc.weight class_embed" to ignore some inconsistent parameters.

**Comment by yspaik** [comment]
Thank you for your advice! It works.

**Comment by SangbumChoi** [comment]
> When fine-tuning a COCO pre-trained model on your custom dataset, the main difference between two datasets is the number of classes.
> 
> As said by @gd1925, the arg "dn_labebook_size" should be equal to or larger than the number of classes.
> 
> When loading pre-trained models, we suggest using "--pretrain_model_path" to specify a pre-trained model, and using "--finetune_ignore label_enc.weight class_embed" to ignore some inconsistent parameters.

@SlongLiu Hi did you use same fine-tuning method (importing all weights except for cls_embedding weight) as mentioned in this line Object365 to COCO?

**Comment by SlongLiu** [comment]
> > When fine-tuning a COCO pre-trained model on your custom dataset, the main difference between two datasets is the number of classes.
> > 
> > As said by @gd1925, the arg "dn_labebook_size" should be equal to or larger than the number of classes.
> > 
> > When loading pre-trained models, we suggest using "--pretrain_model_path" to specify a pre-trained model, and using "--finetune_ignore label_enc.weight class_embed" to ignore some inconsistent parameters.
> 
> @SlongLiu Hi did you use same fine-tuning method (importing all weights except for cls_embedding weight) as mentioned in this line Object365 to COCO?

Yes, exactly.

**Comment by wulamao** [comment]
> 

Actually, 'dn_labebook_size' is 'dn_labe**l**book_size' .
