### ISSUE TITLE
inference per image

### ISSUE THREAD

**Issue by xueyyao** [IDEACVR/DINO#25]
I am trying to use this amazing project for object detection task on my own dataset. I am now confusing how to get inference  on an image/a dataset (推理单张图片或一个数据集). Could you release a sample code for inferencing? Thanks!

**Comment by SlongLiu** [comment]
you can refer to this notebook https://github.com/IDEACVR/DINO/blob/main/inference_and_visualization.ipynb

**Comment by xueyyao** [comment]
Thanks for your help. Your advice helps a lot!
