### ISSUE TITLE
hflip and vflip

### ISSUE THREAD

**Issue by xueyyao** [IDEACVR/DINO#35]
Hi there,

I notice that we use the horizontal flip in data augmentation. I am trying to use vertical flip and rotation for data augmentation. However, I am wondering what the line of code means:

boxes = boxes[:, [2, 1, 0, 3]] * torch.as_tensor([-1, 1, -1, 1]) + torch.as_tensor([w, 0, w, 0])
target['masks'] = target['mask'].flip(-1)

(datasets.transform.py)

If I want to flip vertically, what should I change for the boxes and masks? Also, what should I change if I want to rotate? Thanks for your help!

**Comment by SlongLiu** [comment]
I think the question is out of the scope of our paper. I suggest searching for the problem on the internet. There are some example codes for reference: https://github.com/Paperspace/DataAugmentationForObjectDetection/blob/master/data_aug/data_aug.py, or use the albumentations lib: https://albumentations.ai/docs/api_reference/augmentations/transforms/.

**Comment by xueyyao** [comment]
> I think the question is out of the scope of our paper. I suggest searching for the problem on the internet. There are some example codes for reference: https://github.com/Paperspace/DataAugmentationForObjectDetection/blob/master/data_aug/data_aug.py, or use the albumentations lib: https://albumentations.ai/docs/api_reference/augmentations/transforms/.

Thanks for your advice!
