### ISSUE TITLE
What happens when there are no target in the Dataset ?

### ISSUE THREAD

**Issue by thad75** [IDEACVR/DINO#38]
hi,
In COCO Dataset, few images are non labeled, I was wondering how you handle these type of data for the denoising and matching part ?
Thanks

**Comment by SuperHenry2333** [comment]
In this situation, there will be no denoising part. In the matching part, all queries are encouraged to predict no object.

**Comment by xueyyao** [comment]
Does this mean that our model supports using both negative and positive samples?

**Comment by SuperHenry2333** [comment]
> Does this mean that our model supports using both negative and positive samples?

sure

**Comment by xueyyao** [comment]
> Collaborator

Could you help explain why we can train negative samples in this project?

**Comment by Li-Qingyun** [comment]
@xueyyao When there is no target in the current sample, DINO should have the ability to classify all targets as no obj, so there will be loss_cls that need to be backward. In the code, It can be seen that the authors have done a lot of clever detailings on this kind of samples to prevent this special case from raising errors in distributed mode.
