### ISSUE TITLE
a question about use_ema in main.py

### ISSUE THREAD

**Issue by xueyyao** [IDEACVR/DINO#39]
Hi there,

Thanks for your help and listening!

When I look at the main.py, I notice that "use_ema" appears frequently. However, I find that this will set "False" in config. What do you design it for? What tasks do we need to use it? If we use this project for object detection, do I need to set something for this part? 
<img width="239" alt="Screenshot 2022-07-26 at 9 42 36 AM" src="https://user-images.githubusercontent.com/71103425/180904627-b659955c-c667-4a9d-abdd-12a97750ac77.png">

**Comment by SlongLiu** [comment]
ema is a trick to boost models. You can set it to True and may get better performance.

**Comment by xueyyao** [comment]
Could you explain more about "ema"? What kind of trick is it? Thanks!

**Comment by SlongLiu** [comment]
It means ```exponential mean average```. You may find some useful information [here](https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/ema#:~:text=Exponential%20Moving%20Average%20(EMA)%20is,data%20that%20is%20more%20current.)

**Comment by xueyyao** [comment]
Thanks for your reply? Do we use it for faster convergence (because ema will be more sensitive to the change of gradient)?

**Comment by artest08** [comment]
That is a very interesting concept. Are the experiments of the paper with ema or not? Is there any ablation study related with that? Thanks in advance

**Comment by SlongLiu** [comment]
The results in our paper are performed without ema.
