### ISSUE TITLE
Why learnable content queries in Mixed query selection is helpful?

### ISSUE THREAD

**Issue by JarvisUSTC** [IDEACVR/DINO#4]
After reading the paper, I have a confusion about Mixed query selection. I think the learnable content queries will mismatch with the positional queries from the output of Encoder. So I am confused about the improvement of mixed query selection. Just setting content queries to zeros maybe achieve better performance. I want to know if you ever visualized the content queries after training. Look forward  to your reply.

**Comment by SlongLiu** [comment]
At first, the learnable content queries are used to match positional keys from the encoder only in the cross-attention modules. 
Besides, we find DETR with learnable content queries will get better results compared with all zero content queries used in vanilla DETR. It is worth noting that the learnable content queries are used in Deformable DETR as well. 
For the visualization, we will try to do it as you suggested. Thanks for your valuable questions and suggestions.

**Comment by JarvisUSTC** [comment]
The learnable content queries are actually used in one stage Deformable DETR. But it is also worth noting that the positional queries are also learnable as content queries. And in DINO, I think it is implemented based on two stage Deformable DETR and the content queries are not learnable in two stage Deformable DETR. On the other hand, the attention maps are composed of content attention maps and positional attention maps. Hence, if the content queries are not related to positional queries, the whole attention maps will be confused.

**Comment by SlongLiu** [comment]
> The learnable content queries are actually used in one stage Deformable DETR. But it is also worth noting that the positional queries are also learnable as content queries. And in DINO, I think it is implemented based on two stage Deformable DETR and the content queries are not learnable in two stage Deformable DETR. On the other hand, the attention maps are composed of content attention maps and positional attention maps and positional queries are from the prediction of Encoder. Hence, if the content queries are not related to positional queries, the whole attention maps will be confused. Thanks for your reply.

Sorry for my late reply. I believe it is a good question, which confused us for a long time as well. In my opinion, one reason for the better results of mixed query selection might be the special patterns of selected queries. For example, the first query has larger possibilities to be a token at the top left of images.
