### ISSUE TITLE
category_map_str

### ISSUE THREAD

**Issue by xueyyao** [IDEACVR/DINO#41]
When I read the code in detail, I find that there is a class called "label2compat" in coco.py (datasets). I am wondering if I need to change it when I want to use my dataset to train the model (different num_class)?

<img width="970" alt="Screenshot 2022-07-27 at 1 26 43 PM" src="https://user-images.githubusercontent.com/71103425/181168167-13821de2-1a8a-4abd-98d0-3a859a6d0b45.png">

**Comment by SlongLiu** [comment]
We did not use this class/function in our models, hence you can just ignore it.

**Comment by xueyyao** [comment]
> We did not use this class/function in our models, hence you can just ignore it.

Thanks!
