### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\20825\\AppData\\Local\\Temp\\tmpt11h2ul9\\tmp2fdhjty4.py'

### ISSUE THREAD

**Issue by myseverus** [IDEACVR/DINO#43]
thanks for your greate work.
Recently, I wanted to train my own dataset
 bash scripts/DINO_train.sh COCODIR
The result error:

Not using distributed mode
Loading config file from config/DINO/DINO_4scale.py
Traceback (most recent call last):
  File "main.py", line 398, in <module>
    main(args)
  File "main.py", line 100, in main
    cfg = SLConfig.fromfile(args.config_file)
  File "C:\Users\20825\Desktop\DINO-main\util\slconfig.py", line 188, in fromfile
    cfg_dict, cfg_text = SLConfig._file2dict(filename)
  File "C:\Users\20825\Desktop\DINO-main\util\slconfig.py", line 86, in _file2dict
    shutil.copyfile(filename,
  File "C:\anaconda\envs\dino_detr\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\20825\\AppData\\Local\\Temp\\tmpt11h2ul9\\tmp2fdhjty4.py'
Thank you for your answer

**Comment by htomov-gm** [comment]
I am getting the same error.

**Comment by SuperHenry2333** [comment]
> 

The reason is that in Windows, the temp directory is non-writable. You should change line 82 of util\slconfig.py into somewhere else. For example, some directory under your home dir.

**Comment by nomurakeiya** [comment]
@SuperHenry2333 I'm getting tha same error, can you explain more detail?
which file? which line? how to chage?

**Comment by zjh21** [comment]
Changing the temp directory did not work for me. In the function 'def _file2dict', I added a line 'temp_config_file.close()' after 'temp_config_file = tempfile.NamedTemporaryFile(dir=temp_config_dir, suffix='.py')' and the problem was solved.
