### ISSUE TITLE
CUDA indexSelectLargeIndex problem

### ISSUE THREAD

**Issue by BubblyYi** [IDEACVR/DINO#44]
Hi,

Thanks for your amazing work!

When I try to train the object365 dataset, a cuda error will be triggered like '/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [281,0,0$
, thread: [32,0,0] Assertion  srcIndex < srcSelectDimSize failed.'
at [https://github.com/IDEACVR/DINO/blob/24f3567e162c75f0323cf4a1ed2d5bf6e36bee52/models/dino/dn_components.py#L70]()
Here are some error messages that may be useful:
![error](https://user-images.githubusercontent.com/10595758/181256096-9fb175c7-e0d6-47e7-b95f-dc45fdbbb61f.png)
Here is my config
![cof](https://user-images.githubusercontent.com/10595758/181256567-1d45bbca-5111-4ee8-8c13-95da7ffb2b20.png)

Looking forward to your reply.

**Comment by SlongLiu** [comment]
You may need to tune the parameter "dn_labebook_size" to larger than the num_classes, 366 here. see #23 for more details.

**Comment by CHR-Postgraduate** [comment]
I also encountered this problem. How did you solve it? Moreover, modifying the  "dn_labebook_size" parameter has no effect.
