### ISSUE TITLE
Why is nums_classes set to 91 and but，the actual number of categories in coco's dataset is 80

### ISSUE THREAD

**Issue by lihuikenny** [IDEACVR/DINO#46]
@IDEACVR

**Comment by SuperHenry2333** [comment]
COCO has 90 categories that have class id 1~90. nums_classes is set to 91 for convenience so that we do not need to map class id to 0~79.

**Comment by lihuikenny** [comment]
@SuperHenry2333 【中文说了哈】我看作者的代码，初始化注册模型的时候都是用91，那么模型的最后分类层应该是【N,91】,但是实际是只有80类【加背景81】，当然我的经验告诉我，实际类别是可以小于预设的分类层数量【不能大于】。后面我尝试设置nums_classes=81，却不行。不知道读取coco数据的时候，底层是怎么转换的？也许我需要去研究一下coco数据读取底层的代码，如果您知道其中的原因，还请解惑，谢谢。

**Comment by BinhuiXie** [comment]
Hi, @lihuikenny

This discussion https://github.com/facebookresearch/detr/issues/108 might be helpful!
