### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by TonyzBi** [IDEACVR/DINO#49]
I met the isuue of memory leak,  when It run on second epoch, the  memory run out with memory size of 64G. anyone have ever been in the same situation ?

**Comment by SuperHenry2333** [comment]
We did not meet the problem. Could you share more detail?

**Comment by TonyzBi** [comment]
Thanks for you kindly reply. It shows that memory usage increased continuously, it will run out 64G when trained 2 epoches on coco Dataset, by the way, I trained the project with distribute lauch.

**Comment by TonyzBi** [comment]
I Noticed that [COCO Mask API is leaking memory when used with Multithreading 
 (https://github.com/cocodataset/cocoapi/issues/202#top)
