### ISSUE TITLE
Question about batch_size

### ISSUE THREAD

**Issue by xueyyao** [IDEACVR/DINO#50]
Hi there,

I am trying to change the batch_size in config file to fit my dataset. However, when I set batch_size over 10, the system will show runtime error. Do you set something for the batch_size?

**Comment by SuperHenry2333** [comment]
Could you share more detail about the error?

**Comment by xueyyao** [comment]
<img width="1425" alt="截屏2022-08-01 13 57 55" src="https://user-images.githubusercontent.com/71103425/182082253-be8fa079-2f91-4cad-b2f8-3d21447d33b9.png">

**Comment by SuperHenry2333** [comment]
Maybe you can refer to this https://discuss.pytorch.org/t/runtimeerror-received-0-items-of-ancdata/4999

**Comment by xueyyao** [comment]
Thanks!
