### ISSUE TITLE
why small batch_size

### ISSUE THREAD

**Issue by xueyyao** [IDEACVR/DINO#51]
Hi there,

I notice your team since DAB-DETR. Your work leaves me great impression. However, I have a question about the small batch size. Why do you use such a small batch size? Do you run an experiment on it? Thanks for your help~

**Comment by FengLi-ust** [comment]
Batch size 16 is commonly used in many DETR-like models. We have tried other batch size before, but it seems batch size 16 achieves the best performance.

We are also curious about this phenomenon, but we can not provide an in-depth analysis of it now (:

**Comment by xueyyao** [comment]
> Batch size 16 is commonly used in many DETR-like models. We have tried other batch size before, but it seems batch size 16 achieves the best performance.
> 
> We are also curious about this phenomenon, but we can not provide an in-depth analysis of it now (:

However, I reviewed the paper and the project on the github. They say that the batch_size you use is 2 for distributed mode.

**Comment by SuperHenry2333** [comment]
> > Batch size 16 is commonly used in many DETR-like models. We have tried other batch size before, but it seems batch size 16 achieves the best performance.
> > We are also curious about this phenomenon, but we can not provide an in-depth analysis of it now (:
> 
> However, I reviewed the paper and the project on the github. They say that the batch_size you use is 2 for distributed mode.

We use batch size 2 or 4 per GPU and 8 or 4 GPUs in total.

**Comment by FengLi-ust** [comment]
Batch size 2 for each GPU, totally 8 GPUs, so total batch size is 16.

**Comment by xueyyao** [comment]
> Batch size 2 for each GPU, totally 8 GPUs, so total batch size is 16.

Thanks for your help!
