### ISSUE TITLE
RuntimeError: selected index k out of range， topK out of range when doing evalutaion

### ISSUE THREAD

**Issue by Pattorio** [IDEACVR/DINO#52]
Hi, really appreciate your brilliant work.

I am trying to use DINO to train my own dataset with 2 classes. 
I modified  `num_classes=3` and `dn_labelbook_size = 3` (I think it is necessary), then start training. After one epoch, I get this error when doing evaluation.

Any advice？

Thanks.

```
Traceback (most recent call last):
  File "main.py", line 448, in <module>
    main(args)
  File "main.py", line 334, in main
    wo_class_error=wo_class_error, args=args, logger=(logger if args.save_log else None)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/opt/tiger/DINO/engine.py", line 169, in evaluate
    outputs = model(samples, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/tiger/DINO/models/dino/dino.py", line 274, in forward
    hs, reference, hs_enc, ref_enc, init_box_proposal = self.transformer(srcs, masks, input_query_bbox, poss,input_query_label,attn_mask)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/tiger/DINO/models/dino/deformable_transformer.py", line 356, in forward
    topk_proposals = torch.topk(enc_outputs_class_unselected.max(-1)[0], topk, dim=1)[1] # bs, nq
RuntimeError: selected index k out of range
```

**Comment by FengLi-ust** [comment]
It seems this problem lies in query selection to select topk proposals. This error indicates the `topk` is larger than the size of 
enc_outputs_class_unselected. 

You can refer to [this issue](https://discuss.pytorch.org/t/pred-output-topk-maxk-1-true-true-runtimeerror-selected-index-k-out-of-range/126940) for more details.

Maybe your image is too small that enc_outputs_class_unselected  do not have enough features to select the top 900 queries?  You can try using a smaller number of queries or larger images.

**Comment by Pattorio** [comment]
> It seems this problem lies in query selection to select topk proposals. This error indicates the `topk` is larger than the size of enc_outputs_class_unselected.
> 
> You can refer to [this issue](https://discuss.pytorch.org/t/pred-output-topk-maxk-1-true-true-runtimeerror-selected-index-k-out-of-range/126940) for more details.
> 
> Maybe your image is too small that enc_outputs_class_unselected do not have enough features to select the top 900 queries? You can try using a smaller number of queries or larger images.

Thank you so much for your rely.

As you say, I find that the output feature sizes are too small. I am using resnet50 as backbone (batch=1, hidden_dim=256)  and the output feature sizes are : 
1, 255, 64, 10 
1, 255, 32, 5
1, 255, 16, 3
1, 255, 8, 2
Therefore, `enc_outputs_class_unselected` do not have enough features to select the top 900 queries.

It seems the input image is only 224x40. 
But image should be resized to fixed size when evaluating. I set max_size = max(scales) = 512.

Any ideas?

```
    if image_set in ['val', 'eval_debug', 'train_reg', 'test']:

        if os.environ.get("GFLOPS_DEBUG_SHILONG", False) == 'INFO':
            print("Under debug mode for flops calculation only!!!!!!!!!!!!!!!!")
            return T.Compose([
                T.ResizeDebug((1280, 800)),
                normalize,
            ])   

        return T.Compose([
            T.RandomResize([max(scales)], max_size=max_size),
            normalize,
        ])
```

**Comment by SuperHenry2333** [comment]
Maybe you can reduce the number of queries.

**Comment by Pattorio** [comment]
> Maybe you can reduce the number of queries.

Thank you so much. I am now using this way to continue my training.

And I find there is an image with size (512, 80) (after resizing) causing this problem, lol.

Thank you again for your reply and work!

**Comment by Pattorio** [comment]
Two more question:
1. Have you ever had experiments for DINO under different number of queries?
2. When training with customer dataset, except `num_classes` and `dn_labelbook_size`, are there any variables related to the number of classes need to be change?

**Comment by SuperHenry2333** [comment]
> Two more question:
> 
> 1. Have you ever had experiments for DINO under different number of queries?
> 2. When training with customer dataset, except `num_classes` and `dn_labelbook_size`, are there any variables related to the number of classes need to be change?

Q1: Reducing 900 queries to 300 queries will slightly reduce the performance (about 0.5 AP).
Q2: No other hyper-parameter to change.

**Comment by EddieEduardo** [comment]
When I test with num_classes >= 3, this error will not raise, but if I test with num_classes <=2, this error will definitely raise.

**Comment by EddieEduardo** [comment]
This issue happened due to the num_select set in configs, try to small this parameter according to **enc_outputs_class_unselected.max(-1)[0]**, ensuring num_select is less than or at least equal to the length of target dimension.
