### ISSUE TITLE
a bug about hidden_dim

### ISSUE THREAD

**Issue by TengQinglong** [IDEACVR/DINO#55]
According to the code, in DINO, hidden_dim is not only the number of neurals in MLP, but also the length of tokens and querys，but when I try to change the hidden_dim to 64, there is a error in deformable_transformer.py
![image](https://user-images.githubusercontent.com/45716174/182790618-4dae6bc2-c55c-4b36-9f1b-321091bacc5c.png)
I found the function .utils.gen_sineembed_for_position return has a fixed shape[-1], which is 512, twice hidden_dim, so I make it adapt to hidden_dim, and it can be trained.
By the way, will decreasing hidden_dim affect the model performance greatly?

**Comment by FengLi-ust** [comment]
It will affect the performance,  we have tried hidden dim 256 and 128, and found 128 will decrease the performance by around 0.5 AP. We are not sure what will happen when further set it to 64.

**Comment by TengQinglong** [comment]
Thank you for your reply.
