### ISSUE TITLE
the model which uses Swin backbone finally acquire 56.8 mAP, which is more lower than the result in papers, why?

### ISSUE THREAD

**Issue by jishuaijian** [IDEACVR/DINO#57]

**Comment by SuperHenry2333** [comment]
The model with 63.3 AP is pre-trained on Object365 and finetuned on COCO with 5 feature map scales and large image sizes, while the opensource one is without the above mentioned techniques.

**Comment by mitming** [comment]
> The model with 63.3 AP is pre-trained on Object365 and finetuned on COCO with 5 feature map scales and large image sizes, while the opensource one is without the above mentioned techniques.

I have tried train swin-L with 5 feature map scales and large image sizes, however, only 58.8 mAP is obtained.  I am not sure all the hyper-parameters are correct in the released configs.

**Comment by SuperHenry2333** [comment]
> > The model with 63.3 AP is pre-trained on Object365 and finetuned on COCO with 5 feature map scales and large image sizes, while the opensource one is without the above mentioned techniques.
> 
> @SuperHenry2333
> 
> I have tried train swin-L with 5 feature map scales and large image sizes, however, only 58.8 mAP is obtained. I am not sure all the hyper-parameters are correct in the released configs. Could you please check that?

58.8 is a similar result as what we got with 5 scales.

**Comment by mitming** [comment]
> > > The model with 63.3 AP is pre-trained on Object365 and finetuned on COCO with 5 feature map scales and large image sizes, while the opensource one is without the above mentioned techniques.
> > 
> > 
> > @SuperHenry2333
> > I have tried train swin-L with 5 feature map scales and large image sizes, however, only 58.8 mAP is obtained. I am not sure all the hyper-parameters are correct in the released configs. Could you please check that?
> 
> 58.8 is a similar result as what we got with 5 scales.

@SuperHenry2333 

Based on the existing experimental results, can I infer that pre-training of objects365 is crucial for DINO? Because the highest result in the paper is 63.3, which is much better than 58.8 trained directly on COCO.

**Comment by SuperHenry2333** [comment]
> > > > The model with 63.3 AP is pre-trained on Object365 and finetuned on COCO with 5 feature map scales and large image sizes, while the opensource one is without the above mentioned techniques.
> > > 
> > > 
> > > @SuperHenry2333
> > > I have tried train swin-L with 5 feature map scales and large image sizes, however, only 58.8 mAP is obtained. I am not sure all the hyper-parameters are correct in the released configs. Could you please check that?
> > 
> > 
> > 58.8 is a similar result as what we got with 5 scales.
> 
> @SuperHenry2333
> 
> Based on the existing experimental results, can I infer that pre-training of objects365 is crucial for DINO? Because the highest result in the paper is 63.3, which is much better than 58.8 trained directly on COCO.

Yes, it is.

**Comment by mitming** [comment]
> > > > > The model with 63.3 AP is pre-trained on Object365 and finetuned on COCO with 5 feature map scales and large image sizes, while the opensource one is without the above mentioned techniques.
> > > > 
> > > > 
> > > > @SuperHenry2333
> > > > I have tried train swin-L with 5 feature map scales and large image sizes, however, only 58.8 mAP is obtained. I am not sure all the hyper-parameters are correct in the released configs. Could you please check that?
> > > 
> > > 
> > > 58.8 is a similar result as what we got with 5 scales.
> > 
> > 
> > @SuperHenry2333
> > Based on the existing experimental results, can I infer that pre-training of objects365 is crucial for DINO? Because the highest result in the paper is 63.3, which is much better than 58.8 trained directly on COCO.
> 
> Yes, it is.

Thanks a lot! I understand that the paper has not yet been drafted, and I will update the problems I have encountered in this question. I hope to get your answers in the future. Thank you again for your reply and contribution.

**Comment by PascualWalaris** [comment]
Can you upload the pre-trained model on the Objects365 dataset with a SwinL backbone (which obtains the best results on both COCO val2017 (63.2AP) and test-dev (63.3AP))? Therefore, we can get a state-of-the-art model for object detection.
