### ISSUE TITLE
Question about two_stage_type in DeformableTransformer class in the your code

### ISSUE THREAD

**Issue by seonhoon1002** [IDEACVR/DINO#58]
Hello, Thanks to share your great job.

I'm a beginer of transformer architecture, so It is a trivial question

I don't know what means of "two_stage_type" in "config/DINO/DINO_4scale.py" and "models/dino/deformable_transformer.py". Does this mean selection mode of "Query Selection" in "DINO" or having a other meaning?

**Comment by SuperHenry2333** [comment]
"two_stage_type" can be "no" or "standard". It decides whether use two_stage (query selection) or not. Our model use "standard" by default.

**Comment by seonhoon1002** [comment]
Aha, I undestand.
Thanks :)
