### ISSUE TITLE
RuntimeError: "ms_deform_attn_forward_cuda" not implemented for 'Half'

### ISSUE THREAD

**Issue by a1112** [IDEACVR/DINO#59]
RuntimeError: "ms_deform_attn_forward_cuda" not implemented for 'Half'

**Comment by a1112** [comment]
does not support fp16 yet

**Comment by SlongLiu** [comment]
Could you please provide more details about the error?

**Comment by SlongLiu** [comment]
Oh I see. The deformable attention ops did not support fp16 yet. We will fix this in the next update.

**Comment by SlongLiu** [comment]
We fix the bug by converting all tensors to fp32 when performing deformable attention.
