### ISSUE TITLE
Why conditional query does not suit DINO but suit DAB-DETR?

### ISSUE THREAD

**Issue by JarvisUSTC** [IDEACVR/DINO#6]
Hi, why conditional query does not suit DINO but suit DAB-DETR? The reason is in CDN? Look forward to your reply.

**Comment by SlongLiu** [comment]
The main reason might be the deformable attention, which is not sensible to the positional queries.

**Comment by SlongLiu** [comment]
Yes, there is no conditional query in DAB-Deformable-DETR, whose code is available now.

**Comment by JarvisUSTC** [comment]
Thanks!
