### ISSUE TITLE
question about decoder type

### ISSUE THREAD

**Issue by seonhoon1002** [IDEACVR/DINO#60]
There are 'sa', 'ca', 'ffn' in decoder module, but I don't understand what they mean. 

Could you tell me what they are?

**Comment by SuperHenry2333** [comment]
> There are 'sa', 'ca', 'ffn' in decoder module, but I don't understand what they mean.
> 
> Could you tell me what they are?

They denote self-attention, cross-attention, and feedforward network respectively.

**Comment by seonhoon1002** [comment]
Can I ask a one more question?

There are 'sa', 'ca_label', 'ca_content' in decoder_sa_type in config file. 

What do these mean?

**Comment by SlongLiu** [comment]
"sa" is the standard self-attention.
"ca_label" replace the self-attention with cross-attention to labels. More specifically, we learn label embeddings for each class, which will be used as keys and values during attention.
"ca_content" is the same as cross-attention. The model will perform two cross-attention operations in each layer if using this args.

**Comment by seonhoon1002** [comment]
Ok I understood
Thanks!
