### ISSUE TITLE
Training supposedly run but does nothing

### ISSUE THREAD

**Issue by fschvart** [IDEACVR/DINO#63]
I'm not sure exactly what's happening, but when I run the training, specifically selecting cuda:0 as my device I ran into a weird issue. 

I don't get an error message and the I get the "Start training" message, but don't see anything happening afterwards. At the same time I see that my RAM gets fully grabbed by the model (I have 32gb) and the GPU isn't doing anything, its memory is empty and temperature is low. CPU also doesn't seem to be doing much. 

Where could the problem be? 
Thanks!

**Comment by SuperHenry2333** [comment]
> I'm not sure exactly what's happening, but when I run the training, specifically selecting cuda:0 as my device I ran into a weird issue.
> 
> I don't get an error message and the I get the "Start training" message, but don't see anything happening afterwards. At the same time I see that my RAM gets fully grabbed by the model (I have 32gb) and the GPU isn't doing anything, its memory is empty and temperature is low. CPU also doesn't seem to be doing much.
> 
> Where could the problem be? Thanks!

It seems you do not install the CUDA correctly or your pytorch does not support CUDA.

**Comment by fschvart** [comment]
Thank you so much for your response!
You're probably right, I used another machine that I previously used, that also has a RTX3090 and now while running the test.py after installation I get CUDA out of memory. Is it because I use only 1 GPU and not 8?

**Comment by SuperHenry2333** [comment]
> Thank you so much for your response! You're probably right, I used another machine that I previously used, that also has a RTX3090 and now while running the test.py after installation I get CUDA out of memory. Is it because I use only 1 GPU and not 8?

It is not about the number of GPUs. You should reduce the batch size to 1 or 2.

**Comment by fschvart** [comment]
Hi, 
Thanks, this was super helpful!
Last question (hopefully): I'm trying to train the model on a custom dataset that has the JSON annotation in a COCO format. 
Does it matter if the image sizes aren't at the exact same dimensions as the COCO dataset?(COCO images are 640x480, some of my images are 640x427 and other are 1920x1080)

The first epoch completes training but it crashes during the evaluation phase with the following message:

C:\Users\InjectoFORTY\miniconda3\envs\mmseg\lib\site-packages\torch\utils\checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
C:\DINO\models\dino\dino.py:680: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  topk_boxes = topk_indexes // out_logits.shape[2]
Traceback (most recent call last):
  File "C:\DINO\main.py", line 398, in <module>
    main(args)
  File "C:\DINO\main.py", line 311, in main
    test_stats, coco_evaluator = evaluate(
  File "C:\Users\InjectoFORTY\miniconda3\envs\mmseg\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\DINO\engine.py", line 236, in evaluate
    res_info = torch.cat((_res_bbox, _res_prob.unsqueeze(-1), _res_label.unsqueeze(-1)), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 900 but got size 300 for tensor number 1 in the list.


Does this has to do with the various images dimensions? If I lower the number of queries form 900 to 300, would that solve the problem? 

Thanks!

**Comment by SuperHenry2333** [comment]
@fschvart You can have a try. It seems that your bug is because the numbers of selected predictions are different. You can debug the code to find out the reason.

**Comment by fschvart** [comment]
@SuperHenry2333 Thanks, it worked and the bbox results look good.
How can I get the instance mask? I looked at the inference notebook and looked at the output of the model and I'm not sure what I"m missing, but I couldn't find any mask parameters.

My goal is eventually to do instance/panoptic segmentation.

Thanks!

**Comment by SuperHenry2333** [comment]
@fschvart DINO currently does not support segmentation.

**Comment by Furkanicten1239** [comment]
> 

How did u solve that problem. I'm encountering with the same thing.
