### ISSUE TITLE
How can i run it ,i can't do it

### ISSUE THREAD

**Issue by Linyuda** [IDEACVR/DINO#64]
![image](https://user-images.githubusercontent.com/22868340/183597533-69c6a417-1ecb-4fb8-b00f-27c06f3f5669.png)
![image](https://user-images.githubusercontent.com/22868340/183597573-7a7e4f5c-32f7-4db8-882b-7122a996960e.png)
i don't know how to solve it 
the bash srcipts i can't run either

**Comment by SuperHenry2333** [comment]
> ![image](https://user-images.githubusercontent.com/22868340/183597533-69c6a417-1ecb-4fb8-b00f-27c06f3f5669.png) ![image](https://user-images.githubusercontent.com/22868340/183597573-7a7e4f5c-32f7-4db8-882b-7122a996960e.png) i don't know how to solve it the bash srcipts i can't run either

Please follow the examples in README to run the code.
