### ISSUE TITLE
Out of memory mid epoch 

### ISSUE THREAD

**Issue by DableUTeeF** [IDEACVR/DINO#65]
I trained the Swin 4 scale on Colab with

```
!python main.py \
	--output_dir logs/DINO/R50-MS4 -c config/DINO/DINO_4scale_swin.py --coco_path /content/Chula-ParasiteEgg-11 \
    --pretrain_model_path /content/backbone/checkpoint0011_4scale_swin.pth --num_workers 0 \
	--options dn_scalar=100 embed_init_tgt=TRUE \
	dn_label_coef=1.0 dn_bbox_coef=1.0 use_ema=False \
	dn_box_noise_scale=1.0 backbone_dir=. batch_size=2
```
The code work just fine but at some point I got CUDA OOM error. Changing `batch_size` and adding `--amp` only delay the issue. 

I noticed that `max mem:` keep increasing after every few iterations. I want to think this is because multi-scaling but the resizing uses `T.RandomResize` so the fact that memory usage progressively increasing doesn't make sense.

What else could be the problem?

**Comment by SuperHenry2333** [comment]
The memory cost increases in the first few iterations but becomes stable afterward. Maybe your GPU memory is not enough for Swin-L model.

**Comment by DableUTeeF** [comment]
You're right. Reducing input size or use smaller model solve this.
