### ISSUE TITLE
run_with_submitit

### ISSUE THREAD

**Issue by zhaofh1115** [IDEACVR/DINO#66]
Excuse me, I trained your code with distributed, using script "scripts/ dino_train_submitit. sh", and then reported an error that "no shared folder available". After carefully checking, I found that I need to have a directory like "comp_robot" in my computer. What is this directory for?
![image](https://user-images.githubusercontent.com/48617861/183668766-65f98c54-1e91-4102-9699-573adbc8c576.png)

**Comment by SuperHenry2333** [comment]
> Excuse me, I trained your code with distributed, using script "scripts/ dino_train_submitit. sh", and then reported an error that "no shared folder available". After carefully checking, I found that I need to have a directory like "comp_robot" in my computer. What is this directory for? ![image](https://user-images.githubusercontent.com/48617861/183668766-65f98c54-1e91-4102-9699-573adbc8c576.png)

You need to change the path "/comp_robot/{user}/experiments" to a valid path on your machine.
