### ISSUE TITLE
Annotation format

### ISSUE THREAD

**Issue by LoaferCH** [IDEACVR/DINO#69]
It is unclear for me what annotation format should be used. 

Coco annotation format is **[x,y,width,height]**
However in here: https://github.com/IDEACVR/DINO/blob/5be6a1a312d457c90ca7d5baa5f69a81489b5fae/datasets/coco.py#L378-L383
It is stated that x0,y0,x1,y1 format is needed and then it gets converted into -> cx,cy,w,h.

So what should it be?

Thank you.

**Comment by SuperHenry2333** [comment]
@LoaferCH I think the comment here is wrong. The init format should be  [x,y,width,height].
