### ISSUE TITLE
run_with_submitit ?

### ISSUE THREAD

**Issue by mitming** [IDEACVR/DINO#70]
Hi, @FengLi-ust @SuperHenry2333 

What are the machine requirements for `run_with_submitit`? I try to run `run_with_submitit.sh` on 8 machines, but always get the error:
```
ValueError: LocalExecutor can use only one node. Use nodes=1
```

Can we use `slurm` instead of `submitit` ?

**Comment by SuperHenry2333** [comment]
Sure, you can use slurm dirrectlly. You should set dist_url of each machine the same. You can refer to this https://zhuanlan.zhihu.com/p/373395654 for more information.

**Comment by mitming** [comment]
> Sure, you can use slurm dirrectlly. You should set dist_url of each machine the same. You can refer to this https://zhuanlan.zhihu.com/p/373395654 for more information.

Glad to know that, I will try it. Thanks a lot.
