### ISSUE TITLE
save_results

### ISSUE THREAD

**Issue by abbasmammadov** [IDEACVR/DINO#71]
I have tried --save_results feature with several datasets, but it triggers an issue that outputs['pred_boxes'][0] has a shape of (900, 4) but results[0]['scores'] and results[0]['labels'] have shapes of (300). Since save_results concatenates those by unsqueezeing latter 2 on dim=-1, the error occurs here. I tried with several models and custom datasets but the error looks inevitable. Can you please consider this issue? Thanks in advance!
<img width="1153" alt="Screen Shot 2022-08-11 at 6 55 51 PM" src="https://user-images.githubusercontent.com/101348852/184108965-ac545e02-26e0-4909-af1d-afc6e5156b9f.png">

**Comment by SuperHenry2333** [comment]
Hi @abbasmammadov , I'm sorry for the bug.  Actually, although there is a "save_results" option, we never used it. We may support "save_results" in the next version of our code.

**Comment by abbasmammadov** [comment]
Ohh, I see. Thank you very much for your clear and prompt reply :)
