### ISSUE TITLE
backbone_dir

### ISSUE THREAD

**Issue by id4su** [IDEACVR/DINO#74]
![image](https://user-images.githubusercontent.com/87803154/184475451-3644603b-0cec-425d-9805-667711f99946.png)
![image](https://user-images.githubusercontent.com/87803154/184475550-68b6041d-6f3f-4492-97fa-35da3c831738.png)
when I want to test this model ,there is a question,i guess that is I don't have the pretained model,can you give the download path to me ?

**Comment by SuperHenry2333** [comment]
https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth

**Comment by id4su** [comment]
thank you very much

**Comment by id4su** [comment]
![image](https://user-images.githubusercontent.com/87803154/185558630-7a0d1ec4-f96c-4e75-b952-22b57605f69a.png)
A little busy the last few days.When I need to download this,there is a problem,may I get this permission?

**Comment by xucheng-920** [comment]
> https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth

This download link is restricted, I hope to be able to give a permission. thanks.
