### ISSUE TITLE
question about dn_box_noise_scale

### ISSUE THREAD

**Issue by Li-Qingyun** [IDEACVR/DINO#75]
![image](https://user-images.githubusercontent.com/79644233/184542726-52539e95-9e22-40cc-b4e1-3790686f0a66.png)
dn box noise scale is 0.4 at the end of the paper, but 1 in the launch.sh code and Multi-scale setting.
![image](https://user-images.githubusercontent.com/79644233/184542708-b2de69fb-3bf0-41c2-8865-5ec172df0cd4.png)

**Comment by IDEACVR** [comment]
@Li-Qingyun Sorry, It is a typo in Table 8. You should follow dn_box_noise_scale=1.0 in the code to reproduce our results. We will fix the error in the next version of the paper.

**Comment by Li-Qingyun** [comment]
@IDEACVR OK, Thanks!
