### ISSUE TITLE
questions about ablations 

### ISSUE THREAD

**Issue by MengLcool** [IDEACVR/DINO#78]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/39439083/184824966-c4b50f2e-f8cf-4fbe-ba6c-6d9a7948534a.png">
Hello, Thanks for your great job. I am wondering to know the details about the difference between row1 and row2.   
Does the performance gain mainly caused by using deformable transformers in the decoder?

**Comment by SuperHenry2333** [comment]
Hi, there are mainly three reasons for the improvement: 1. Dynamic DN groups; 2. Hyperparameter tuning; 3. deformable decoder.

**Comment by MengLcool** [comment]
Thank you for your reply!
I am also curious about row \# 6 performance 47.9, which is different from the 49.0 in Table. 1. Could you give more details about the difference between them?  
Is it caused by increasing 300 queries to 900 queries

**Comment by SuperHenry2333** [comment]
@MengLcool Please refer to #17 for this question.
