### ISSUE TITLE
What is the content query of CDN queries?

### ISSUE THREAD

**Issue by zengwang430521** [IDEACVR/DINO#8]
Hi, I'm confused about what the content query of CDN queries is. Is it the same as the normal learnable content queries?

Looking forward to your reply. Thanks in advance!

**Comment by SuperHenry2333** [comment]
The content parts of CDN queries are taken as ground-truth label embeddings with noises same as in DN-DETR.

**Comment by zengwang430521** [comment]
Thanks for you reply.

**Comment by owen24819** [comment]
Hi following up on this question,

I see that an indicator was used in DN-DETR but dropped in DINO-DETR. I quoted below the description of the indicator from the DN-DETR.

> We also append an indicator to label embedding. The indicator is 1 if a query belongs to the denoising part and 0 otherwise.

Can you comment why you dropped the indicator? I couldn't find anywhere in the paper mentioning this.

Also very nice work!
