### ISSUE TITLE
how to save the evaled pictures ?

### ISSUE THREAD

**Issue by skyfallsss** [IDEACVR/DINO#84]
How to save the evaled pictures?
I want to see the results after using the trained model.

**Comment by FengLi-ust** [comment]
Pass `savedir` to the visuilizer will work.

**Comment by oooyc** [comment]
> How to save the evaled pictures?
> I want to see the results after using the trained model.

Hey, body. Have you solve this problem? I also want to save the evaded pictures, but I don't know where to start. Thank you so much if you could tell me about it.
