### ISSUE TITLE
questions about batch size and num_gpus settings

### ISSUE THREAD

**Issue by Li-Qingyun** [IDEACVR/DINO#94]
Hello, the description of batch_size and num_gpu in the paper is not very clear, I'm working on aligning training performance and I would like to confirm with you.

All the DINO-4scale exp, including R50 and Swin-L backbones, are 2 samples_per_gpu and 8 gpus.
All the DINO-5scale exp, including R50 and Swin-L backbones, are 1 samples_per_gpu and 16 gpus on 2 nodes. 

Are the above understandings right?

**Comment by FengLi-ust** [comment]
Yes. You can use different number of gpu as long as you gpu has enough memory. The key is to keep the total batchsize 16.

**Comment by Li-Qingyun** [comment]
@FengLi-ust Thanks for your reply!
