### ISSUE TITLE
Dynamic DN groups

### ISSUE THREAD

**Issue by fushh** [IDEACVR/DINO#97]
Thanks for your great work!
As mentioned in Appendix D.1,
> Considering that the number of objects in one image in COCO dataset ranges from 1 to 80, this design is inefficient and results in excessive memory consumption. To address this problem, we propose to fix the number of DN queries and dynamically adjust the number of groups for each image according to its number of objects.

However, it seems that DINO is implemented in the same way as DN-DETR.

**Comment by SuperHenry2333** [comment]
You can refer to this [line](https://github.com/IDEACVR/DINO/blob/8758cf02146f306dc36babab4fff1f09c114c682/models/dino/dn_components.py#L43) which obtain the number of dn groups by considering the number of objects in images.

**Comment by fushh** [comment]
Yes, according to this line, we can dynamically adjust the number of groups for each batch but not for each image. I think we can further utilize the memory by designing image-specific masks. Will these three implementations affect performance a lot? (fix groups for the entire dataset, fix groups for each batch, or change it according to different images)

**Comment by SuperHenry2333** [comment]
@fushh Your proposed three ideas are interesting. The first and second looks like the original dn-detr and dynamic dn respectively. Dynamic dn can help to add more dn queries, so it improves the performance by 0.5~1.0 AP. The third one have a similar performance with the second one.
